FROM ubuntu:latest
RUN apt-get update && apt-get -y upgrade && apt-get -y install python3-pip build-essential
WORKDIR /usr/src/app
COPY requirements.txt joey/
RUN pip3 install -r joey/requirements.txt
COPY . joey/
RUN pip3 install -e joey
WORKDIR /usr/src/app/joey
