name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_cpu:
    name: Run pytest on Docker (CPU)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.5
      - run: docker build -f Dockerfile_CPU -t devitocodes/joey:latest .
      - run: docker run devitocodes/joey:latest pytest
  test_openmp:
    name: Run pytest on Docker (CPU with OpenMP)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.5
      - run: docker build -f Dockerfile_CPU -t devitocodes/joey:latest .
      - run: docker run -e DEVITO_LANGUAGE=openmp devitocodes/joey:latest pytest
