name: Tests (CPU)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run pytest on Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -f Dockerfile_CPU -t devitocodes/joey:latest .
      - run: docker run devitocodes/joey:latest pytest
